version: '3.4'

volumes:
  # UMD Customization
  streaming:
  # End UMD Customization
  database:
  fedora:
  solr:
  npms:
  # UMD Customization
  # data:
  work:
  # End UMD Customization

networks:
  internal:
  external:

services:
  db: &db-avalon
    image: postgres:14-alpine
    volumes:
      - database:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_DB=avalon
      - POSTGRES_PASSWORD=password
    networks:
      internal:
  db-test:
    <<: *db-avalon
    volumes: []

  fedora: &fedora
    # UMD Customization
    image: docker.lib.umd.edu/fedora:4.7.5-avalon-7.5.1
    # End UMD Customization
    depends_on:
      - db
    volumes:
      - fedora:/data
    environment:
      - JAVA_OPTIONS=-Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.home=/data
    networks:
      internal:
  fedora-test:
    <<: *fedora
    volumes: []

  solr: &solr
    # UMD Customization
    image: docker.lib.umd.edu/solr:avalon-7.5.1
    # End UMD Customization
    volumes:
      - ./solr/conf:/opt/solr/avalon_conf
      - solr:/var/solr
    command:
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    networks:
      internal:
  solr-test:
    <<: *solr
    volumes:
      - ./solr/conf:/opt/solr/avalon_conf

  hls:
    # UMD Customization
    image: docker.lib.umd.edu/nginx:avalon-7.5.1-umd-1
    # End UMD Customization
    environment:
      - AVALON_DOMAIN=http://avalon:3000
    # UMD Customization
    volumes:
      - streaming:/data
    # End UMD Customization
    ports:
      - '8880:80'
    networks:
      external:

  redis: &redis
    image: redis:alpine
    networks:
      internal:
  redis-test:
    <<: *redis

  avalon: &avalon
    # UMD Customization
    image: docker.lib.umd.edu/avalon:7.5.1-umd-1
    # End UMD Customization
    build:
      context: .
      target: dev
    command: bash -c "/docker_init.sh && bundle exec rails server -b 0.0.0.0"
    depends_on:
      - db
      - fedora
      - solr
      - redis
      - hls
    environment:
      # UMD Customization
      - APP_NAME=avalon
      - SETTINGS__DOMAIN__PROTOCOL=http
      - SETTINGS__DOMAIN_HOST=av-local
      - SETTINGS__DOMAIN_PORT=3000
      - BUNDLE_FLAGS=--with development postgres --without production test
      - ENCODE_WORK_DIR=/streamfiles
      - CONTROLLED_VOCABULARY=config/controlled_vocabulary.yml
      - DATABASE_URL=postgres://postgres:password@db/avalon
      - DIGITAL_COLLECTIONS_URL=https://digital.lib.umd.edu/
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - RAILS_ENV=development
      - RAILS_ADDITIONAL_HOSTS=avalon
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SECRET_KEY_BASE=abcd
      - SOLR_URL=http://solr:8983/solr/avalon
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - SETTINGS__STREAMING__STREAM_DEFAULT_QUALITY=medium
      - SETTINGS__STREAMING__HTTP_BASE=http://localhost:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - SAML_ISSUER=av-local:3000
      - UMD_HANDLE_PREFIX=1903.1
      - UMD_HANDLE_REPO=avalon
      # End UMD Customization
    volumes:
      # UMD Customization
      - .:/home/app/avalon
      - ./masterfiles:/masterfiles
      - streaming:/streamfiles
      - npms:/home/app/avalon/node_modules
      # End UMD Customization
    ports:
      - '3000:3000'
    networks:
      internal:
      external:
    stdin_open: true
    tty: true

  test:
    <<: *avalon
    command: >
      bash -c "/docker_init.sh && tail -f /dev/null"
    depends_on:
      - db-test
      - fedora-test
      - solr-test
      - redis-test
    environment:
      - DATABASE_URL=postgresql://postgres:password@db-test/avalon
      # UMD Customization
      - DIGITAL_COLLECTIONS_URL=https://digital-test.lib.umd.edu/
      # End UMD Customization
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - SETTINGS__REDIS__HOST=redis-test
      - SETTINGS__REDIS__PORT=6379
      - FEDORA_URL=http://fedora-test:8080/fedora/rest
      - SOLR_URL=http://solr-test:8983/solr/avalon
      - RAILS_ENV=test
      - BUNDLE_FLAGS=--with aws test postgres --without production
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    ports: []

  worker:
    <<: *avalon
    command: dumb-init -- bash -c "bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    ports: []
# UMD Customization
  # minio:
  #   image: minio/minio:RELEASE.2019-10-12T01-39-57Z
  #   command: minio server /data
  #   environment:
  #     MINIO_ACCESS_KEY: minio
  #     MINIO_SECRET_KEY: minio123
  #   volumes:
  #     - data:/data
  #   ports:
  #     - 9000:9000
  #   networks:
  #     internal:
  #     external:
  #   healthcheck:
  #     test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3

  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
  #     /usr/bin/mc mb -p myminio/fcrepo myminio/masterfiles myminio/derivatives myminio/supplementalfiles;
  #     /usr/bin/mc policy set download myminio/derivatives;
  #     /usr/bin/mc policy set download myminio/supplementalfiles;
  #     exit 0;
  #     "
  #   networks:
  #     internal:
# End UMD Customization

  cypress:
    network_mode: host
    image: cypress/included:3.8.2
    depends_on:
      - avalon
    entrypoint: cypress run -C spec/cypress/cypress.json
    working_dir: /e2e
    volumes:
      - ./:/e2e
      - npms:/e2e/node_modules
