# frozen_string_literal: true

# UMD Customization
# Turns the provisioned scenarios into the three things that consume them: a markdown table
# for manual testing, a JSON manifest for the Cypress spec, and a Prometheus target file for
# blackbox probing of the canaries.
class UmdAccessScenarios
  class Reporter
    MANIFEST_PATH = Rails.root.join('spec/cypress/fixtures/access_scenarios.json')
    BLACKBOX_PATH = Rails.root.join('umd_docs/monitoring/blackbox_targets.yml')

    def initialize(host: nil)
      @host = normalize_host(host.presence || Settings.domain&.host || 'http://av-local:3000')
    end

    def markdown_table
      personas = entries.flat_map { |entry| entry[:expectations].keys }.uniq
      lines = [header_row(personas), separator_row(personas)]
      lines += entries.map { |entry| body_row(entry, personas) }
      ([legend] + lines).join("\n")
    end

    def write_manifest
      FileUtils.mkdir_p(File.dirname(MANIFEST_PATH))
      File.write(MANIFEST_PATH, JSON.pretty_generate(host: @host, scenarios: entries))
      MANIFEST_PATH
    end

    # Emits a Prometheus file_sd target list for the canary items. The expected status is
    # carried as a label so a probe can be alerted on when it stops matching, and the
    # vantage point is left to the scraping Prometheus to attach.
    def write_blackbox_targets
      FileUtils.mkdir_p(File.dirname(BLACKBOX_PATH))
      File.write(BLACKBOX_PATH, blackbox_yaml)
      BLACKBOX_PATH
    end

    def entries
      @entries ||= UmdAccessScenarios.all.filter_map do |scenario|
        media_object = lookup(scenario)
        next if media_object.nil?

        { slug: scenario.slug, description: scenario.description, id: media_object.id,
          url: item_url(media_object), canary: scenario.canary?,
          token_urls: token_urls(media_object), expectations: scenario.expectations }
      end
    end

    private

      # Settings.domain.host carries no scheme, and a URL without one is useless to both
      # Cypress and blackbox_exporter.
      def normalize_host(host)
        host = host.to_s.sub(%r{/\z}, '')
        return host if host.match?(%r{\Ahttps?://})

        local = host.start_with?('localhost', '127.0.0.1', 'av-local', 'test.host')
        "#{local ? 'http' : 'https'}://#{host}"
      end

      def lookup(scenario)
        MediaObject.where(other_identifier_ssim: scenario.identifier).first ||
          MediaObject.where(title_tesi: scenario.title).first
      end

      def item_url(media_object)
        "#{@host}/media_objects/#{media_object.id}"
      end

      def token_urls(media_object)
        AccessToken.where(media_object_id: media_object.id).index_by { |token| token_kind(token) }
                   .transform_values { |token| "#{item_url(media_object)}?access_token=#{token.token}" }
      end

      def token_kind(token)
        return :revoked if token.revoked?
        return :expired if token.expiration.past?
        return :stream if token.allow_streaming?

        :download
      end

      def legend
        "Item page: 200 = renders, 401 = Restricted Content. " \
          "browse: visible/hidden in search results. Blank = not asserted.\n"
      end

      def header_row(personas)
        "| Scenario | URL | #{personas.join(' | ')} |"
      end

      def separator_row(personas)
        "| --- | --- | #{personas.map { '---' }.join(' | ')} |"
      end

      def body_row(entry, personas)
        cells = personas.map { |persona| format_outcome(entry[:expectations][persona]) }
        "| #{entry[:slug]} | #{entry[:url]} | #{cells.join(' | ')} |"
      end

      def format_outcome(outcome)
        return '' if outcome.blank?

        parts = []
        parts << outcome[:page].to_s if outcome.key?(:page)
        parts << "browse:#{outcome[:browse]}" if outcome.key?(:browse)
        parts << (outcome[:stream] ? 'stream' : 'no stream') if outcome.key?(:stream)
        parts << 'download' if outcome[:download]
        parts.join(', ')
      end

      def blackbox_yaml
        targets = UmdAccessScenarios.canaries.filter_map { |scenario| blackbox_target(scenario) }
        <<~YAML
          # Generated by `rails umd:access_scenarios:report FORMAT=blackbox` -- do not edit by hand.
          #
          # Consumed by two blackbox_exporter probers, one on-campus/VPN and one outside, so
          # that the IP-dependent rows differ between vantage points. Attach the vantage as a
          # label in the Prometheus scrape config, not here.
          #{targets.to_yaml.sub(/\A---\n/, '')}
        YAML
      end

      def blackbox_target(scenario)
        entry = entries.find { |e| e[:slug] == scenario.slug }
        return nil if entry.nil?

        { 'targets' => [entry[:url]],
          'labels' => { 'scenario' => scenario.slug,
                        'expected_status_anonymous' => anonymous_status(scenario).to_s,
                        'expected_status_in_range' => in_range_status(scenario).to_s } }
      end

      def anonymous_status(scenario)
        scenario.expectation_for(:anonymous)[:page] || 200
      end

      def in_range_status(scenario)
        scenario.expectation_for(:ip_in_range)[:page] || anonymous_status(scenario)
      end
  end
end
# End UMD Customization
