domain:
  host: test.host
  # UMD Customization
  # Override UMD-customized "port: 3000", in "config/settings.yml"
  port: 80
  # End UMD Customization
dropbox:
  upload_uri: smb://test.host/dropbox
auth:
  # UMD Customization
  # Override UMD-customized "registerable: false", in "config/settings.yml"
  registerable: true
  # End UMD Customization
  configuration:
    - :name: Avalon Lti OAuth
      :provider: :lti
      :hidden: true
      :params:
        :oauth_credentials:
          key: 'secret'
encoding:
  engine_adapter: test
email: 
  mailer:
